# 
# Paleobiology Database - classic backend image
# 
# This file builds the preload image, which has a bunch of necessary packages and
# takes 45 minutes or more to build. The main Dockerfile then uses this to build
# the final image by copying in the source code and other local content.

FROM perl:5.26-threaded AS paleobiodb_classic_preload

RUN apt-get update && \
    apt-get -y install apt-utils && \
    apt-get -y install mariadb-client && \
    apt-get -y install beanstalkd && \
    cpanm DBI && \
    cpanm DBD::mysql && \
    cpanm Dancer && \
    cpanm Moo && \
    cpanm Moose && \
    cpanm DBIx::Class && \
    cpanm CHI && \
    cpanm IO::File && \
    cpanm YAML && \
    cpanm Email::Sender::Simple && \
    cpanm Email::MIME::Kit && \
    cpanm Email::Sender && \
    cpanm Config::JSON && \
    cpanm Ouch && \
    cpanm Log::Log4perl && \
    cpanm Plugin::Tiny && \
    cpanm Beanstalk::Client && \
    cpanm DateTime && \
    cpanm DateTime::Format::MySQL && \
    cpanm DBIx::Class::UUIDColumns && \
    cpanm DBIx::Class::TimeStamp && \
    cpanm DBIx::Class::InflateColumn::Serializer && \
    cpanm Data::GUID && \
    cpanm Crypt::Eksblowfish::Bcrypt && \
    cpanm String::Random && \
    cpanm Cache::FastMmap && \
    cpanm Data::Serializer && \
    cpanm Text::CSV_XS && \
    cpanm Class::Date && \
    cpanm Mail::Mailer && \
    cpanm Wing::Client && \
    cpanm JSON::XS && \
    cpanm Server::Starter && \
    cpanm Starman && \
    cpanm Plack::Middleware::MethodOverride && \
    cpanm Plack::Middleware::SizeLimit && \
    cpanm Plack::Middleware::CrossOrigin && \
    cpanm Net::Server::SS::PreFork && \
    cpanm Template::Toolkit && \
    cpanm Dancer::Logger::Log4perl

RUN apt-get install -y vim

RUN cpanm Email::MIME::Kit::Renderer::TT && \
    cpanm IO::Socket::SSL
