# 
# Paleobiology Database - Classic backend image
# 
# This file is used to build the preload image for the Paleobiology Database Classic
# backend service. It installs a long list of necessary packages, and takes 45 minutes
# or more to build. The Dockerfile found in this directory then uses the preload image
# as a base to build the Classic backend container image very quickly by copying in the
# source code, configuration file and other local content. You can build this preload
# image locally using the command 'pbdb build classic preload'.

FROM perl:5.32-threaded AS paleomacro_classic_preload

RUN apt-get update && \
    apt-get -y install apt-utils && \
    apt-get -y install mariadb-client && \
    apt-get -y install beanstalkd && \
    apt-get install -y vim && \
    cpanm DBI && \
    cpanm DBD::mysql && \
    cpanm Dancer && \
    cpanm Moo && \
    cpanm Moose && \
    cpanm DBIx::Class && \
    cpanm CHI && \
    cpanm IO::File && \
    cpanm YAML && \
    cpanm Email::Sender::Simple && \
    cpanm Email::MIME::Kit && \
    cpanm Email::MIME::Kit::Renderer::TT && \
    cpanm Email::Sender && \
    cpanm Config::JSON && \
    cpanm DateTime && \
    cpanm DateTime::Format::MySQL && \
    cpanm DBIx::Class::UUIDColumns && \
    cpanm DBIx::Class::TimeStamp && \
    cpanm DBIx::Class::InflateColumn::Serializer && \
    cpanm DBIx::Class::DeploymentHandler && \
    cpanm Data::GUID && \
    cpanm Crypt::Eksblowfish::Bcrypt && \
    cpanm Ouch
    
RUN cpanm --force Plugin::Tiny && \
    cpanm Log::Log4perl && \
    cpanm Plugin::Tiny && \
    cpanm Beanstalk::Client && \
    cpanm String::Random && \
    cpanm Cache::FastMmap && \
    cpanm Data::Serializer && \
    cpanm Text::CSV_XS && \
    cpanm Class::Date && \
    cpanm Mail::Mailer && \
    cpanm Wing::Client && \
    cpanm JSON::XS && \
    cpanm Server::Starter && \
    cpanm Starman && \
    cpanm Plack::Middleware::MethodOverride && \
    cpanm Plack::Middleware::SizeLimit && \
    cpanm Plack::Middleware::CrossOrigin && \
    cpanm Net::Server::SS::PreFork && \
    cpanm Template::Toolkit && \
    cpanm Dancer::Logger::Log4perl && \
    cpanm App::Cmd::Setup && \
    cpanm IO::Socket::SSL && \
    cpanm --force Term::ReadLine::Gnu

RUN apt-get -y install locales && \
    apt-get -y install tzdata && \
    locale-gen --purge en_US.UTF-8
